### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by oGalatico** [PresentKim/HotBox-PMMP#1]
TypeError: "strrev() expects parameter 1 to be string, integer given" (EXCEPTION) in "HotBox/src/kim/present/hotbox/HotBox" at line 81

TypeError: "Argument 2 passed to pocketmine\nbt\tag\IntTag::__construct() must be of the type integer, null given, called in C:\Users\pc\Desktop\PocketMine-MP\plugins\HotBox\src\kim\present\hotbox\HotBox.php on line 124" (EXCEPTION) in "vendor/pocketmine/nbt/src/tag/IntTag" at line 39

**Comment by PresentKim** [comment]
Is there a way to reproduce this error? I don't know why this error occurred

Than, I released first version the 1.0.0-ALPHA.
Can you test it with use 1.0.0-ALPHA version?

Link : [PresentKim/HotBox-PMMP@releases/1.0.0-ALPHA](https://github.com/PresentKim/HotBox-PMMP/releases/tag/1.0.0-ALPHA)

**Comment by PresentKim** [comment]
I fixed in release 1.0.2-ALPHA.

Link : [PresentKim/HotBox-PMMP@releases/1.0.2-ALPHA](https://github.com/PresentKim/HotBox-PMMP/releases/tag/1.0.2-ALPHA)
